### ISSUE TITLE
update conda-forge package

### ISSUE THREAD

**Issue by lriesebos** [CabbageDevelopment/qasync#105]
not sure if this is the correct place, but is it possible to get 0.25.0, 0.26.1, and newer versions on conda-forge? currently only <=0.24.2 are available https://anaconda.org/conda-forge/qasync/files. we are currently suffering from a bug that is fixed in 0.25.0 onwards, but can't get the package in conda.

**Comment by hosaka** [comment]
Hi, I am unfamiliar with how anacconda manages packages, is there a maintainer you can contact? This repo only pushes releases to pypi.

**Comment by lriesebos** [comment]
ah ok, I think that happens here in a semi-automatic way: https://github.com/conda-forge/qasync-feedstock. notice that 0.25.0 has an automatic PR that was not merged yet, see https://github.com/conda-forge/qasync-feedstock/pull/14#issuecomment-1817898878. the workflows for newer versions seem to fail. not sure if there is any way for you and @ales-erjavec to collaborate and get that working again.
