### ISSUE TITLE
Maintained badge shows no

### ISSUE THREAD

**Issue by philippkarg** [CabbageDevelopment/qasync#119]
There is a little bug with the "maintained" badge. It currently shows that the project is not maintained (which was a little confusing as the README later states that the project is maintained).

![image](https://github.com/CabbageDevelopment/qasync/assets/73899270/2df536d9-b002-46c3-94d5-28feba8d886e)

**Comment by st-walker** [comment]
Well the real question is, then, is qasync maintained or not?

**Comment by hosaka** [comment]
I've been a bit busy recently, i'll go over the PRs in the near future and sort out the maintaned badge in the process.
