### ISSUE TITLE
unnecessary warnings

### ISSUE THREAD

**Issue by hartytp** [CabbageDevelopment/qasync#18]
cf https://github.com/harvimt/quamash/issues/110

fix was https://github.com/OxfordIonTrapGroup/quamash/commit/2ccf4410fb3912b78bb40db5da7a916c6d770904

**Comment by hartytp** [comment]
Are you actively merging PRs, or should I stick to a fork?

**Comment by TheGreatCabbage** [comment]
> 
> 
> Are you actively merging PRs, or should I stick to a fork?

I am merging PRs :-)

**Comment by hartytp** [comment]
Cool! Okay, I'll spin up a PR shortly.
