### ISSUE TITLE
closing the mainwindow stops the eventloop?

### ISSUE THREAD

**Issue by RYDB3RG** [CabbageDevelopment/qasync#39]
Hi,

is it expected that closing the mainwindow closes the eventloop as well?
In this example, `print_loop` stops immediately after I close the window and following awaits fail with event-loop-stopped exception. 
Is there a way to keep the eventloop around a while longer to do some cleanup work after the window is closed?

```python
import PySide2.QtWidgets
import qasync
import asyncio
import logging

async def print_loop():
    i = 0
    while True:
        logging.info(i)
        i += 1
        await asyncio.sleep(0.5)

async def main(app):
    asyncio.ensure_future(print_loop())
    stop_event = asyncio.Event()
    app.aboutToQuit.connect(stop_event.set)
    label = PySide2.QtWidgets.QLabel('Hello World!')
    label.show()
    await stop_event.wait()
    logging.info("done")
    await asyncio.sleep(10)

logging.basicConfig(level = logging.DEBUG)
app = PySide2.QtWidgets.QApplication()
loop = qasync.QEventLoop(app)
asyncio.set_event_loop(loop)
loop.run_until_complete(main(app))
```

**Comment by eyllanesc** [comment]
@RYDB3RG  If you want the eventloop not to end when all windows are closed then you must use the [`setQuitOnLastWindowClosed`](https://doc.qt.io/qt-5/qguiapplication.html#quitOnLastWindowClosed-prop) function:

```python
app.setQuitOnLastWindowClosed(False)
```
