### ISSUE TITLE
Setting up an event loop in another thread?

### ISSUE THREAD

**Issue by dark-penguin** [CabbageDevelopment/qasync#42]
Is it possible to set up a `qasync` event loop in another thread? If so, how to do it? I could not find any documentation about it. The GUI is in the main thread, and it doesn't really need `asyncio` as much as the worker thread which does all the work.

Since `qasync.QEventLoop()` requires a `QApplication` argument, if I try to call it in a thread, it will probably get the main application event loop instead of a thread loop. But you can't do `qasync.QEventLoop(myThread)`...

In case the question is not clear enough, here is a code example.
```python
import logging
import sys
import datetime
import asyncio
import qasync

from PyQt5.QtCore import QObject, pyqtSlot, QThread
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QWidget, QVBoxLayout


class Logic(QObject):  # Logic to run in a separate thread
    enabled = False

    @pyqtSlot()
    def start(self):
        logger.debug('Start called')
        self.enabled = True
        asyncio.create_task(self.process())

    @pyqtSlot()
    def stop(self):
        logger.debug('Stop called')
        self.enabled = False

    async def process(self):
        while self.enabled:
            logger.debug(f'Processing ({datetime.datetime.now()})...')
            await asyncio.sleep(0.5)


if __name__ == '__main__':
    logging.basicConfig(format='%(levelname)s:%(name)s: %(message)s')
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.DEBUG)

    app = QApplication(sys.argv)
    asyncio.set_event_loop(qasync.QEventLoop(app))

    logic = Logic()

    # Move logic to another thread
    # thread = QThread()
    # logic.moveToThread(thread)
    # thread.start()

    window = QMainWindow()
    window.setCentralWidget(QWidget())
    window.centralWidget().setLayout(QVBoxLayout())

    window.centralWidget().layout().addWidget(QPushButton(text='Start', clicked=logic.start))
    window.centralWidget().layout().addWidget(QPushButton(text='Stop', clicked=logic.stop))

    window.show()

    logger.debug('Launching the application...')
    exit(app.exec_())
```
If you run this as it is, it will work (in a singe thread). If you uncomment the "`Move logic to another thread`" block, it will fail because there is no asyncio event loop for `asyncio.create_task()`. But there is a PyQt loop in this thread, because slots in this thread are working. How do use asyncio+PyQt at the same time in the worker thread as well as the main thread?

**Comment by abxy37** [comment]
`# subclass QThread. override the run function to create an event loop and run forever
class WorkerThread(QThread):
    def run(self):
        loop = qasync.QEventLoop(self)
        asyncio.set_event_loop(loop)
        loop.run_forever()`

overriding function to create a QThread that executes an asyncio loop.

https://stackoverflow.com/questions/67979231/how-to-set-up-a-qasync-event-loop-in-another-thread

**Comment by hosaka** [comment]
Closing this as the SO post explains how to do this pretty well: create your QEventLoop in a separate thread. Copy pasting with better formatting:
```python
# subclass QThread. override the run function to create an event loop and run forever
class WorkerThread(QThread):
    def run(self):
        loop = qasync.QEventLoop(self)
        asyncio.set_event_loop(loop)
        loop.run_forever()
```
