### ISSUE TITLE
remove "Close Application" from future.cancel

### ISSUE THREAD

**Issue by nubonics** [CabbageDevelopment/qasync#46]
Issue:
In the aiohttp_fetch examample: https://github.com/CabbageDevelopment/qasync/blob/master/examples/aiohttp_fetch.py#L76
on line 76, there is a string of "Close Application" that is passed to future.cancel, and .cancel does not take any arguments, so there is alot of complaining by the debugger because of this and could lead to some confusion for people [like myself] that used this example, as there isn't much documentation for qasync.

Solution:
- remove the string from the future.cancel call

Appreciation
- Thank you!!! For making a modern async library available for the public when building pyqt5 / pyside2 applications!
  This is awesome! So thank you for all that you do with qasync :)

**Comment by TheGreatCabbage** [comment]
Thanks for spotting this. And thanks for the kind words, I've been a bit burned-out on this project but it's good to know that any time I spend is appreciated! (I do need to give credit to the developers who worked on `quamash` and `asyncqt`, and the contributors to `qasync` itself - they've done most of the work!)
