### ISSUE TITLE
Is this project no longer maintained?

### ISSUE THREAD

**Issue by nrbnlulu** [CabbageDevelopment/qasync#64]
in the readme it says the it is but there is a label that says the opposite

**Comment by hosaka** [comment]
@nrbnlulu Hi, it's maintained to the best abiliy. Do you have some pressing issue?

**Comment by nrbnlulu** [comment]
hi thanks, generally that was the question :smile:, I tend to be suspicious before i add another dependency...
but if you are asking, I would like to know if there is a support for pyside6?

**Comment by hosaka** [comment]
@nrbnlulu PySide6 is currently tested with the github workflow. As for python 3.10, it hasn't been tested but might very well work.
