### ISSUE TITLE
qasync doesn't work with Python 3.11

### ISSUE THREAD

**Issue by MateuszKrawczuk** [CabbageDevelopment/qasync#68]
After updating to python 3.11 I'm no longer able to launch application:
```
    qasync.run(main())
  File "/path/venv/lib/python3.11/site-packages/qasync/__init__.py", line 821, in run
    return asyncio.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 93, in run
    raise RuntimeError(
RuntimeError: Runner.run() cannot be called from a running event loop
sys:1: RuntimeWarning: coroutine 'main' was never awaited

Process finished with exit code 1
```

**Comment by zhusihan-python** [comment]
got the same error with windows 10 python3.11.1 qasync 0.23.0

**Comment by zhusihan-python** [comment]
exception raised in this line
![image](https://user-images.githubusercontent.com/23504604/208387176-7e092d1e-06d8-489d-9c05-a29e874e7e98.png)]
events._get_running_loop() got QIOCPEventLoop which comes from qasync __init__, 
it is not running state actually in print
`runner events._get_running_loop() <QIOCPEventLoop running=False closed=False debug=False>`

**Comment by baha2046a** [comment]
For me, no problem on 3.11
have you set the event loop at start?

    loop = qasync.QEventLoop(app)
    asyncio.set_event_loop(loop)

**Comment by zhusihan-python** [comment]
i got the same error after set the event loop
![image](https://user-images.githubusercontent.com/23504604/208810262-30bf243d-b8a0-491d-9300-c0d02e8940ee.png)
maybe its caused by i use QGuiApplication not QApplication

now PySide6 support asyncio official recently, here is an [example](https://codereview.qt-project.org/c/pyside/pyside-setup/+/447812/2/examples/async/minimal/minimal_asyncio.py)
i use the [AsyncHelper](https://github.com/zhusihan-python/Pyside6Examples/blob/main/QGuiApplication_asyncio.py) from it to fix the problem, FYI

**Comment by inst-conductor** [comment]
I'm new to using qasync and ran into this problem today, trying to convert my existing program (with PyQt6) to use qasync under Python 3.11. I tried various versions of baha2046a's suggestion, but nothing seemed to work: I was always told that there was no QApplication instance in effect when trying to retrieve the QEventLoop.

I rolled back to Python 3.10.9 and everything works fine.

If someone gets this to work under 3.11 can you please provide a complete example?

**Comment by zhusihan-python** [comment]
> i got the same error after set the event loop ![image](https://user-images.githubusercontent.com/23504604/208810262-30bf243d-b8a0-491d-9300-c0d02e8940ee.png) maybe its caused by i use QGuiApplication not QApplication
> 
> PySide6 support asyncio official recently, here is an [example](https://codereview.qt-project.org/c/pyside/pyside-setup/+/447812/2/examples/async/minimal/minimal_asyncio.py) i use the [AsyncHelper](https://github.com/zhusihan-python/Pyside6Examples/blob/main/QGuiApplication_asyncio.py) from it to fix the problem, FYI

i found that Qt AsyncHepler might have a memory leak problem, my python process memory usage increase 3M per seconds doing nothing.
switch to qasync, the memory usage is stable.
here is an example of qasync works on python3.11, replace qasync.run with loop run
```
app = QGuiApplication()
loop = qasync.QEventLoop(app)
asyncio.set_event_loop(loop)
# qasync.run(main())
t = loop.create_task(main())
loop.run_until_complete(t)
app.exec()
```

**Comment by laomaiweng** [comment]
So I ran into this issue with 3.11 as well and the problem seems to be that the `QEventLoop` spawned by the `DefaultQEventLoopPolicy` set in `qasync.run` registers itself as the running event loop with `asyncio.events._set_running_loop(self)` in `_QEventLoop.__init__`. Shortly after spawning the event loop through the policy, `asyncio.runners.Runner.run` checks that there's no currently running event loop, and bails since there now is one.

Traceback for the call to `_set_running_loop`:

```
  File "/home/user/foo.py", line 172, in <module>
    qasync.run(amain(parser.parse_args()))
  File "/usr/lib/python3.11/site-packages/qasync/__init__.py", line 821, in run
    return asyncio.run(*args, **kwargs)
  File "/usr/lib/python3.11/asyncio/runners.py", line 189, in run
    with Runner(debug=debug) as runner:
  File "/usr/lib/python3.11/asyncio/runners.py", line 59, in __enter__
    self._lazy_init()
  File "/usr/lib/python3.11/asyncio/runners.py", line 137, in _lazy_init
    self._loop = events.new_event_loop()
  File "/usr/lib/python3.11/asyncio/events.py", line 806, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "/usr/lib/python3.11/site-packages/qasync/__init__.py", line 799, in new_event_loop
    return QEventLoop(QApplication(sys.argv))
  File "/usr/lib/python3.11/site-packages/qasync/__init__.py", line 353, in __init__
    asyncio.events._set_running_loop(self)
```

Traceback for the check that there's no running loop:

```
Traceback (most recent call last):
  File "/home/user/foo.py", line 172, in <module>
    qasync.run(amain(parser.parse_args()))
  File "/usr/lib/python3.11/site-packages/qasync/__init__.py", line 821, in run
    return asyncio.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 93, in run
    raise RuntimeError(
RuntimeError: Runner.run() cannot be called from a running event loop
```

It's not clear to me however whether the bug lies with `asyncio` or `qasync`…

**Comment by laomaiweng** [comment]
I'm doing this for now:

```python
# the easy way breaks with Python 3.11, so we do the plumbing ourselves to work around it
if sys.version_info.major == 3 and sys.version_info.minor == 11:
    with qasync._set_event_loop_policy(qasync.DefaultQEventLoopPolicy()):
        runner = asyncio.runners.Runner()
        try:
            runner.run(main(args))
        finally:
            runner.close()
else:
    qasync.run(main(args))
```

This way `asyncio.runners.Runner._lazy_init` runs *after* the running event loop check in `asyncio.runners.Runner.run`.
Otherwise `_lazy_init` runs first when entering the `Runner` context manager as shown in the first traceback above.

**Comment by hosaka** [comment]
Support for 3.11 has not been added yet, as indicated in README.md and on the pypi page, 3.6 - 3.9 are supported.
3.10 and 3.11 will probably be added eventually, in the meantime the workaround posted by @laomaiweng works

**Comment by veractor** [comment]
After looking at this in detail, I believe its a bug in qasync to register `QEventLoop`s as the running loop on construction by default, as it is again set in `_QEventLoop.run_until_complete`. I've opened a pull request to fix this.
