### ISSUE TITLE
Processes not completing on exit

### ISSUE THREAD

**Issue by brightmatter** [CabbageDevelopment/qasync#7]
When running the aiohttp example code, closing the app and rerunning it within the same Spyder session requires restarting the kernel. Otherwise, the second time the app is run, it hangs without error.

Python 3.7.6, Spyder 4.1.2

**Comment by SantosJMM** [comment]
Solution https://github.com/CabbageDevelopment/qasync/pull/32#issue-608260238

**Comment by hosaka** [comment]
Closing as fixed.
