### ISSUE TITLE
downgrade unhelpful log message

### ISSUE THREAD

**Issue by hartytp** [CabbageDevelopment/qasync#74]
`qasync` currently logs the Qt version at info level in `__init__` https://github.com/CabbageDevelopment/qasync/blob/88b64c7eeb94993869a83cdbb0dcb86b107d83d3/qasync/__init__.py#L82

I've never found this particularly helpful - it's not something the user normally wants logged and it's easy for them to figure out if they do want to know it. We have an application with a lot of sub processes where these messages are getting a bit annoying. Would you be open to removing / downgrading this message?

**Comment by hosaka** [comment]
Hi, thanks for the report. I agree that the "Using Qt..." message is not particularly useful. The "Forcing use..." based on QT_API env variable can probably remain at info level.

I will remove the "usiung" message next time I'll open a PR that touches __init__.py.
