### ISSUE TITLE
New minor release? 

### ISSUE THREAD

**Issue by dnadlinger** [CabbageDevelopment/qasync#86]
Hi,

Would it be possible to tag and push out a new release of qasync? https://github.com/CabbageDevelopment/qasync/commit/3efd0c2f61d33b9d38830e53dffb3caaec64aba1 in particular is quite a large quality-of-life improvement.

Thanks!

(Apologies for raising this as an issue; not sure what the best way of contacting you would have been.)

**Comment by hosaka** [comment]
Tagged and published https://github.com/CabbageDevelopment/qasync/releases/tag/v0.24.2

**Comment by dnadlinger** [comment]
Thanks!
