### ISSUE TITLE
Github Actions require Read and write permissions for the updated Release workflow

### ISSUE THREAD

**Issue by hosaka** [CabbageDevelopment/qasync#94]
@TheGreatCabbage Could you please adjust this in repo settings?

`Settings > Actions > General > Workflow permissions` should be set to Read repository contents permission

**Comment by TheGreatCabbage** [comment]
I've updated the setting, so hopefully it should work now. Thanks for your continuing work on the project :)

**Comment by hosaka** [comment]
Perfect, all working now! Releases are created automatically when a new tag is pushed to the repo.
