### ISSUE TITLE
Error while updating it on Manjaro

### ISSUE THREAD

**Issue by RicaBenhossi** [CabbageDevelopment/qasync#97]
When updating this app in Manjaro using pamac it breaks because it can´t find the setup.py

![image](https://github.com/CabbageDevelopment/qasync/assets/15204313/0bd759ae-3d14-40e7-b0a5-38785db640ad)

**Comment by hosaka** [comment]
As of version 0.26.1 we use pyproject.toml to package qasync. Please contact the maintainer of AUR package, asking them to update the makepkg script.
